#ifndef LOCAL_LIMIT_H_
#define LOCAL_LIMIT_H_

#define MAX_FILENAME_LENGTH 255
#define MAX_FUNCTION_NAME_LENGTH 255
#define MAX_INCLUDE_LENGTH 255
#define FUNCTION_PROTO_BOUND 100
#define MAX_QUERY_LENGTH 255
#define MAX_TOKEN_LENGTH 100
#define MAX_FUNCTION_TYPE_LENGTH 255
#define MAX_INPUT_LENGTH 255

#endif // LOCAL_LIMIT_H_
